### ISSUE TITLE
Setting up Dragify

### ISSUE THREAD

**Issue by directcuteo** [hawkerboy7/dragify#12]
Hello! I am trying to set up Dragify on an Angular 8 project but since the examples are too rudimentary, I just can't make it work.

I have installed Dragify through npm and I also installed mini-event-emitter same way.
Now on the first try to use it via `let dragify = new Dragify(containers);` it seems that I can't import it, the IDE is not capable to see the library. 
I imported it myself using `import Dragify from "node_modules/dragify/dist/dragify.js"` (don't know if this is how it should) but I still can't make the app run because of the mini-event-emitter dependecy.
I get **`dragify.js:10 Dragify ~ Dragify depends on the MiniEventEmitter.
https://github.com/hawkerboy7/mini-event-emitter
Define it before Dragify`** even if the version of mini-event-emitter installed by npm is the same as the Dragify's dependency require: `0.8.1`.

Can you please help me out setting this up?

**Comment by hawkerboy7** [comment]
Hi @directcuteo,
I haven't done a setup yet in Angular but lets see how I can help :)

It is built and used with [Browserify](http://browserify.org/).
The dist folder you can use when you do not have/use browserify.
I just checked the MiniEventEmitter and it does not have a distribution yet.
I'll add a distribution folder for the MiniEventEmitter, so you can do a manual setup when you do not make use of Browserify.

So at the moment MiniEventEmitter won't work, but once you have the dist file you just have to ensure you import MiniEventEmitter **before** Dragify then the error you've just shown will disappear.

Next since Angular is creating and changing the DOM in 'runtime' you probably should use the [`isContainer`](https://github.com/hawkerboy7/dragify#optionsiscontainer) option instead of `containers`.

**Comment by hawkerboy7** [comment]
@directcuteo Just published a new version of MiniEventEmitter including the distribution folder and files. Good luck, any more questions ask them please! :)
