### ISSUE TITLE
Drag won't start until you mouseup

### ISSUE THREAD

**Issue by Chez** [hawkerboy7/dragify#8]
I Have a div element ( a single container for moving stuff  around in) with other divs in it each with a single image and a mouseover snippet div that raises on mouseover. There is also a click event attached to each div. The images are only 300px wide and about 150 max high. There are not many, 20 max,  each contained in one of the divs. 

You have to click, hold down the mouse and move it then release to start the drag, then click on the area you want the drop which in turn fires the elements own click event. It's a bit of a messy way to do things. Also your set and reset events are firing multiple times and the opaque class is being added twice and not being removed...

**Comment by hawkerboy7** [comment]
Hey Chez. It sounds indeed like some events are not triggered correctly. Can you make a jsFiddle so I can see exactly whats wrong? Based on the explanation only it is hard to debug.
Also you could consider using (Dragula)[https://github.com/bevacqua/dragula]. Tough I'd like it if you used my library, it is not tested yet on a lot of use cases. Dragula is so it may be of better assistance to you.

**Comment by Chez** [comment]
Hi, I don't have time to make a jsfiddle right now, up to my neck in code. I tried Dragula, but that seems to have some issues too. Yours is a lot faster, but on debugging it doesn't seem to call the drop, only the cancel..I might spend another hour to see if I can find out what is going on, but that is all the time I have today. Perhaps it is the minieventemitter causing the problems.

**Comment by hawkerboy7** [comment]
Hi! I understand. I can try to take a look this afternoon, but the problem you describe appears a bit different from the bug I reported so I am not sure I can help well without the jsFiddle. 
Maybe the problem lies with dragging images around. They may behave different from other DOM elements, I have not tested with images yet.
MiniEventEmitter just sends events, so if you say its sending `cancel` instead of `drop` that sound like problem with Dragify not MiniEventEmitter. However you can debug the events from MiniEventEmitter easily if you add the following line to your code:
```
dragify = new Dragify(containers,options);

dragify.settings.trace = true;
dragify.settings.error = true;
```

Now every event emitter by Dragify is being loged in the console as either a warning or a debug message. I hope it helps you in Debugging!

**Comment by Chez** [comment]
Thanks I'll take a look

**Comment by Chez** [comment]
Here's what I'm getting straight off the bat int he console.

MiniEventEmitter ~ emit ~ Event "drag" does not exist
mini-ev....min.js (line 1)
2
MiniEventEmitter ~ emit ~ Event "move" does not exist
mini-ev....min.js (line 1)
2
TypeError: node.className is undefined
	

classes = node.className.split(' ');

**Comment by hawkerboy7** [comment]
Good! The MiniEventEmitter messages are just warnings. They tell you the events `drag` and `move` are being triggered by `Dragify` without a listener being created for them. So that's not an error but expected if you don't have a `.on("move") or . 

Node.clasName is undefined IS the error. Why that happens though I am not sure. I really need the js html and css to figure out whats wrong

**Comment by hawkerboy7** [comment]
@Chez Hey where you able to figure out the problem or create some code so I can take a look? :)

**Comment by hawkerboy7** [comment]
@Chez I am closing this issue, if you have any code examples I can re-open.
